### ISSUE TITLE
Rename project to `aux-eng-docs` (or `aux-eng-playbook`)

### ISSUE THREAD

**Issue by lelia** [wayfair-incubator/aux-eng-playbook#51]
Ahead of publishing these docs to `.github.io`, we should formalize our project naming to use `aux-eng` and either keep the `-docs` suffix or even rename to `-playbook` if that's a more apt description of what this project aims to be. Thoughts?

**Comment by GaryPWhite** [comment]
playbook is good

**Comment by lelia** [comment]
Yea I like `playbook` too, thanks for changing it. I'm reopening this because I'd like to make sure the project references throughout the repository are consistent (eg. replace `auxeng-docs` with `aux-eng-playbook`), which will require its own PR.
